
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class Tablero extends javax.swing.JFrame {
   
   public Boolean[][] fantasma_label = new Boolean[6][6]; 
   public static JLabel[][] arreglo_labels = new JLabel[6][6];
   Boolean poner_fantasmasj1 = true;
   Boolean poner_fantasmasj2 = true;
   public int fantasmas_j1 = 7;
   public int fantasmas_j2 = 8;
   UltimateTablero tb = new UltimateTablero();
   boolean t = false; 
   boolean turno = true;
   ImageIcon icon = new ImageIcon(getClass().getResource("fantasmas-halloween-gifs-156x130[4].gif"));
   
   public static boolean v = false;
    
    
    public Tablero() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        jLabel49.setText("jLabel1");

        jLabel50.setText("jLabel1");

        jLabel52.setText("jLabel1");

        jLabel51.setText("jLabel1");

        jLabel55.setText("jLabel1");

        jLabel56.setText("jLabel1");

        jLabel54.setText("jLabel1");

        jLabel53.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 0, 0));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(153, 0, 0));
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(153, 0, 0));
        jLabel12.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setOpaque(true);

        jLabel13.setBackground(new java.awt.Color(153, 0, 0));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(153, 0, 0));
        jLabel15.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(153, 0, 0));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(153, 0, 0));
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(153, 0, 0));
        jLabel22.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(153, 0, 0));
        jLabel24.setOpaque(true);

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setOpaque(true);

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setOpaque(true);
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(153, 0, 0));
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setOpaque(true);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(153, 0, 0));
        jLabel27.setOpaque(true);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setOpaque(true);

        jLabel29.setBackground(new java.awt.Color(153, 0, 0));
        jLabel29.setOpaque(true);
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(153, 0, 0));
        jLabel32.setOpaque(true);
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(0, 0, 0));
        jLabel31.setOpaque(true);
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel34.setBackground(new java.awt.Color(153, 0, 0));
        jLabel34.setOpaque(true);
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(0, 0, 0));
        jLabel33.setOpaque(true);
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(153, 0, 0));
        jLabel36.setOpaque(true);

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setOpaque(true);
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
             posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(0,1);
        if(pos==true){
           arreglo_labels[0][1].setIcon(icon);
           fantasma_label[0][1] = true;
           fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");    
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
      
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       posicionamiento_de_labels_en_arreglo();
        boolean pos = tb.ubicar_fantasma(1,1);
        if(pos=true)
           arreglo_labels[1][1].setIcon(icon);
        else
            JOptionPane.showMessageDialog(this, "No puede hacer eso");
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      
    }//GEN-LAST:event_formWindowClosing

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
 
        
        //Codigo para ver las posiciones disponibles
        /*int i[][] = tb.verPosiciones(1, 12);
        JOptionPane.showMessageDialog(this, i[0][2]);
        posicionamiento_de_labels_en_arreglo();
        Prueba();*/
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
               posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(0,2);
        if(pos==true){
           arreglo_labels[0][2].setIcon(icon);
           fantasma_label[0][2] = true;
          fantasmas_j1--; 
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
     
       }
      else
       {
          if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
           posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(0,3);
        if(pos==true){
           arreglo_labels[0][3].setIcon(icon);
          fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
          if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
              posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(0,4);
        if(pos==true){
           arreglo_labels[0][4].setIcon(icon);
          fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
 
       }
      else
       {
         if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
                          posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(3,0);
        if(pos==true){
           arreglo_labels[3][0].setIcon(icon);
           fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
                           posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(4,0);
        if(pos==true){
           arreglo_labels[4][0].setIcon(icon);
          fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
                          posicionamiento_de_labels_en_arreglo();

        if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(5,0);
        if(pos==true){
           arreglo_labels[5][0].setIcon(icon);
           fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
  
       }
      else
       {
          if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
           if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(1,2);
        if(pos==true){
           arreglo_labels[1][2].setIcon(icon);
           fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2"); 
       }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
               if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(1,3);
        if(pos==true){
           arreglo_labels[1][3].setIcon(icon);
           fantasmas_j1--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
       }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
     if(fantasmas_j1>0)
       {

        boolean pos = tb.ubicar_fantasma(1,4);
        if(pos==true){
           arreglo_labels[1][4].setIcon(icon);
            fantasmas_j1--;
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
      
       }
      else
       {
           /*
           if(fantasmas_j2 == 7)
           JOptionPane.showMessageDialog(this, "Ahora le toca  el jugador poner fantasmas");
           else 
           JOptionPane.showMessageDialog(this, "No puedes colocar fantasmas aqui, le toca al jugador 2");
           */
             if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(4,1);
        if(pos==true){
           arreglo_labels[4][1].setIcon(icon);
           fantasmas_j2--;
           fantasma_label[4][1]=true;
          // arreglo_labels[4][1].setBackground(Color.red);
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           
           if(fantasma_label[4][1]==true)
           {
                      if(t == false && turno==true){
               jLabel11.setIcon(null);
               fantasma_label[4][1]=false;
               t = true;
               
               
           }else{
               //jLabel34.setIcon(icon);
               t = false;
               JOptionPane.showMessageDialog(null, "Es turno del segundo jugador.");
                      }
           //JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
           }
           else
           {
               if(t==true && fantasma_label[4][1]==false )
               {
                   jLabel11.setIcon(icon);
               }
               else
               JOptionPane.showMessageDialog(null, "Actualmente no hay ninguno fantasma.");
           }
       }
       }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(4,1);
        if(pos==true){
           arreglo_labels[4][1].setIcon(icon);
           fantasmas_j2--;
           fantasma_label[4][1]=true;
          // arreglo_labels[4][1].setBackground(Color.red);
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
                      if(t == false && turno==false){
               jLabel26.setIcon(null);
               t = true;
               
               
           }else{
               jLabel34.setIcon(icon);
               t = false;
               JOptionPane.showMessageDialog(null, "Es turno del primer jugador.");
                      }
           //JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
       if(fantasmas_j1==0 && fantasmas_j2 >0)
       {
            boolean pos = tb.ubicar_fantasma(4,2);
            if(pos==true){
               arreglo_labels[4][2].setIcon(icon);
               fantasmas_j2--;   
               fantasma_label[4][2] = true;
             //  arreglo_labels[4][2].setBackground(Color.red);
            }
            else
            {
                
                JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
            }
       
       }
      else
       {   
           if(fantasmas_j2==0)
           {
               
               JOptionPane.showMessageDialog(this, "ok:");
               //tb.identificar_pos_disponibles(4, 2);
           }
           else
           {
               JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           }
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        
        if(fantasmas_j1==0 && fantasmas_j2 >0)
       {
        boolean pos = tb.ubicar_fantasma(4,3);
        if(pos==true)
        {
           arreglo_labels[4][3].setIcon(icon);
           fantasmas_j2--; 
           fantasma_label[4][3]=true;
           //arreglo_labels[4][3].setBackground(Color.red);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
                    
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
                          if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(4,4);
        if(pos==true){
           arreglo_labels[4][4].setIcon(icon);
           fantasmas_j2--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
                               if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(5,1);
        if(pos==true){
           arreglo_labels[5][1].setIcon(icon);
           fantasmas_j2--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
                                       if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(5,2);
        if(pos==true){
           arreglo_labels[5][2].setIcon(icon);
           fantasmas_j2--;
           fantasma_label[5][2]=true;
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
                                          if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(5,3);
        if(pos==true){
           arreglo_labels[5][3].setIcon(icon);
           fantasmas_j2--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           if(t == false){
               jLabel34.setIcon(null);
               
               
           }else
               jLabel34.setIcon(icon);
           identificar_pos_disponibles(2, 3);
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
                                       if(fantasmas_j1==0 && fantasmas_j2 >0)
       {

        boolean pos = tb.ubicar_fantasma(5,4);
        if(pos==true){
           arreglo_labels[5][4].setIcon(icon);
           fantasmas_j2--;
            
        }
        else{
            JOptionPane.showMessageDialog(this, "No puedes poner el fantasma ahi");
        }
       
       }
      else
       {
           JOptionPane.showMessageDialog(this, "El jugador 1 no ha terminado de posicionar los fantasmas");
           /*
           aquel pijaso de codigo de mover fantasma
           */ 
       }
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        fantasma_label[3][2]=false;
        
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        
        if(fantasmas_j1 == 0 && fantasmas_j2 == 0 && turno== false){
              if(/*fantasma_label[4][4] == false || fantasma_label[] &&*/ t == false){ //Si por lo menos hay una posicion en el arreglo false que se quite y poner una variable t paraa poder mover el icono
               jLabel20.setIcon(null);
               t = true;
               fantasma_label[0][0] = false;
               
           }else /*if( t == true && thislabel = false)*/{
               jLabel20.setIcon(icon);
            t = false;
            turno = true;
           //}else
             //  JOptionPane.showMessageDialog(this, "No hay ninguna posicion disponible para mover el fanstama");
        }
        }
        
        else
        {
            
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
       if(fantasmas_j1 == 0 && fantasmas_j2 == 0 && turno== true){
              if(/*fantasma_label[4][4] == false || fantasma_label[] &&*/ t == false){ //Si por lo menos hay una posicion en el arreglo false que se quite y poner una variable t paraa poder mover el icono
               jLabel17.setIcon(null);
               t = true;
               fantasma_label[1][4] = false;
               
           }else /*if( t == true && thislabel = false)*/{
               jLabel17.setIcon(icon);
            t = false;
            turno = false;
           //}else
             //  JOptionPane.showMessageDialog(this, "No hay ninguna posicion disponible para mover el fanstama");
        }
        }
        else
        {
            
        }
    }//GEN-LAST:event_jLabel17MouseClicked
    //Funcion booleana(posicion del fantasma que queremos mover){
  //if(arreglo1 && arreglo2)
    //if(
//}
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
public void posicionamiento_de_labels_en_arreglo(){
    arreglo_labels[0][0] = jLabel1;
    arreglo_labels[0][1] = jLabel2;
    arreglo_labels[0][2] = jLabel3;
    arreglo_labels[0][3] = jLabel4;
    arreglo_labels[0][4] = jLabel5;
    arreglo_labels[0][5] = jLabel6; 

    arreglo_labels[1][0] = jLabel7;
    arreglo_labels[1][1] = jLabel8;
    arreglo_labels[1][2] = jLabel9;
    arreglo_labels[1][3] = jLabel10; 
    arreglo_labels[1][4] = jLabel11;
    arreglo_labels[1][5] = jLabel12;

    arreglo_labels[2][0] = jLabel13;
    arreglo_labels[2][1] = jLabel14; 
    arreglo_labels[2][2] = jLabel15;
    arreglo_labels[2][3] = jLabel16;
    arreglo_labels[2][4] = jLabel17;
    arreglo_labels[2][5] = jLabel18;

    arreglo_labels[3][0] = jLabel19;
    arreglo_labels[3][1] = jLabel20;
    arreglo_labels[3][2] = jLabel21;
    arreglo_labels[3][3] = jLabel22;
    arreglo_labels[3][4] = jLabel23;
    arreglo_labels[3][5] = jLabel24;

    arreglo_labels[4][0] = jLabel25;
    arreglo_labels[4][1] = jLabel26;
    arreglo_labels[4][2] = jLabel27;
    arreglo_labels[4][3] = jLabel28;
    arreglo_labels[4][4] = jLabel29;
    arreglo_labels[4][5] = jLabel30;

    arreglo_labels[5][0] = jLabel31;
    arreglo_labels[5][1] = jLabel32;
    arreglo_labels[5][2] = jLabel33;
    arreglo_labels[5][3] = jLabel34;
    arreglo_labels[5][4] = jLabel35;
    arreglo_labels[5][5] = jLabel36;
 
    Border border = BorderFactory.createLineBorder(Color.RED);

    int k[][] = tb.verPosiciones(0, 1);
    int p = k[0][1];
    int j = k[0][0];
   // arreglo_labels[p][j].setBorder(border);
    
    //arreglo_labels[p][j].setBackground(Color.yellow);
}
public void Prueba(){
    posicionamiento_de_labels_en_arreglo();
    arreglo_labels[1][1].setBackground(Color.yellow);
    
}
 public void identificar_pos_disponibles(int fila, int columna)
   {
       posicionamiento_de_labels_en_arreglo();
     
       
       fantasma_label[1][3] = false;
       fantasma_label[3][3] = false;
       fantasma_label[2][2] = false;
       fantasma_label[2][4] = false;
     //
       
       if(fantasma_label[fila-1][columna]== false)
        arreglo_labels[fila-1][columna].setBackground(Color.YELLOW);      
       if(fantasma_label[fila+1][columna] == false)
        arreglo_labels[fila+1][columna].setBackground(Color.YELLOW);
       if(fantasma_label[fila][columna+1] == false)
        arreglo_labels[fila][columna+1].setBackground(Color.YELLOW);
       if(fantasma_label[fila][columna-1] == false)
        arreglo_labels[fila][columna-1].setBackground(Color.YELLOW);
       
       //return disponibilidad;
       
   }

}
